In [14]:
from keras.models import Sequential
from keras import optimizers
from keras.layers import Dense, Activation

import numpy as np

In [15]:
X = np.array([[0,3], [2,2], [1,5], [2,4], [-1,10], [100, 100]])

In [16]:
model=Sequential()
model.add(Dense(units=2, activation='relu'))
model.add(Dense(units=256, activation='relu'))
model.add(Dense(units=1))

#sgd = optimizers.SGD(lr=0.02, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer='sgd')


In [17]:
Y=np.array([3,4,6,6,9, 200])

In [18]:
model.fit(X, Y, epochs=1000)

===========] - 0s 271us/step - loss: 5252.3335
Epoch 769/1000
6/6 [==============================] - 0s 208us/step - loss: 5252.3335
Epoch 770/1000
6/6 [==============================] - 0s 253us/step - loss: 5252.3335
Epoch 771/1000
6/6 [==============================] - 0s 204us/step - loss: 5252.3335
Epoch 772/1000
6/6 [==============================] - 0s 206us/step - loss: 5252.3335
Epoch 773/1000
6/6 [==============================] - 0s 254us/step - loss: 5252.3335
Epoch 774/1000
6/6 [==============================] - 0s 205us/step - loss: 5252.3335
Epoch 775/1000
6/6 [==============================] - 0s 282us/step - loss: 5252.3335
Epoch 776/1000
6/6 [==============================] - 0s 229us/step - loss: 5252.3335
Epoch 777/1000
6/6 [==============================] - 0s 274us/step - loss: 5252.3335
Epoch 778/1000
6/6 [==============================] - 0s 392us/step - loss: 5252.3335
Epoch 779/1000
6/6 [==============================] - 0s 210us/step - loss: 5252.3335
Epoch 7

In [19]:
model.predict(np.array([[1,5]]))

array([[37.99991]], dtype=float32)

In [20]:
model.predict(np.array([[2,5]]))

array([[37.99991]], dtype=float32)

In [21]:
model.predict(np.array([[1,2]]))

array([[37.99991]], dtype=float32)

In [22]:
model.predict(np.array([[2,2]]))

array([[37.99991]], dtype=float32)

In [23]:
model.predict(np.array([[100,-250]]))

array([[-405171.25]], dtype=float32)