In [1]:
from keras.models import Sequential
from keras import optimizers
from keras.layers import Dense, Activation

import numpy as np

Using TensorFlow backend.


In [2]:
X = np.array([[0,3], [2,2], [1,5], [2,4], [-1,10]])

In [3]:
model=Sequential()
model.add(Dense(units=2, activation='relu'))
model.add(Dense(units=256, activation='relu'))
model.add(Dense(units=1))

#sgd = optimizers.SGD(lr=0.02, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer='sgd')


In [4]:
Y=np.array([3,4,6,6,9])

In [5]:
model.fit(X, Y, epochs=1000)






Epoch 1/1000





5/5 [==============================] - 1s 101ms/step - loss: 35.0910
Epoch 2/1000
5/5 [==============================] - 0s 538us/step - loss: 32.5833
Epoch 3/1000
5/5 [==============================] - 0s 457us/step - loss: 29.5196
Epoch 4/1000
5/5 [==============================] - 0s 469us/step - loss: 25.9892
Epoch 5/1000
5/5 [==============================] - 0s 414us/step - loss: 21.7583
Epoch 6/1000
5/5 [==============================] - 0s 458us/step - loss: 14.8832
Epoch 7/1000
5/5 [==============================] - 0s 461us/step - loss: 1.8871
Epoch 8/1000
5/5 [==============================] - 0s 381us/step - loss: 1.3368
Epoch 9/1000
5/5 [==============================] - 0s 344us/step - loss: 1.2017
Epoch 10/1000
5/5 [==============================] - 0s 385us/step - loss: 0.9226
Epoch 11/1000
5/5 [==============================] - 0s 395us/step - loss: 0.8660
Epoch 12/1000
5/5 [==============================] - 0s 417us/step - loss: 0.7009
Epoch 13/

Epoch 73/1000
5/5 [==============================] - 0s 363us/step - loss: 0.2645
Epoch 74/1000
5/5 [==============================] - 0s 332us/step - loss: 0.2208
Epoch 75/1000
5/5 [==============================] - 0s 404us/step - loss: 0.2501
Epoch 76/1000
5/5 [==============================] - 0s 345us/step - loss: 0.2102
Epoch 77/1000
5/5 [==============================] - 0s 359us/step - loss: 0.2370
Epoch 78/1000
5/5 [==============================] - 0s 338us/step - loss: 0.2005
Epoch 79/1000
5/5 [==============================] - 0s 355us/step - loss: 0.2250
Epoch 80/1000
5/5 [==============================] - 0s 342us/step - loss: 0.1916
Epoch 81/1000
5/5 [==============================] - 0s 414us/step - loss: 0.2141
Epoch 82/1000
5/5 [==============================] - 0s 329us/step - loss: 0.1834
Epoch 83/1000
5/5 [==============================] - 0s 363us/step - loss: 0.2041
Epoch 84/1000
5/5 [==============================] - 0s 375us/step - loss: 0.1758
Epoch 85/1000
5/

5/5 [==============================] - 0s 420us/step - loss: 0.0990
Epoch 173/1000
5/5 [==============================] - 0s 504us/step - loss: 0.1098
Epoch 174/1000
5/5 [==============================] - 0s 413us/step - loss: 0.0997
Epoch 175/1000
5/5 [==============================] - 0s 416us/step - loss: 0.1108
Epoch 176/1000
5/5 [==============================] - 0s 415us/step - loss: 0.1005
Epoch 177/1000
5/5 [==============================] - 0s 452us/step - loss: 0.1119
Epoch 178/1000
5/5 [==============================] - 0s 478us/step - loss: 0.1013
Epoch 179/1000
5/5 [==============================] - 0s 370us/step - loss: 0.1130
Epoch 180/1000
5/5 [==============================] - 0s 383us/step - loss: 0.1023
Epoch 181/1000
5/5 [==============================] - 0s 373us/step - loss: 0.1142
Epoch 182/1000
5/5 [==============================] - 0s 400us/step - loss: 0.1032
Epoch 183/1000
5/5 [==============================] - 0s 382us/step - loss: 0.1155
Epoch 184/1000
5/5 

Epoch 271/1000
5/5 [==============================] - 0s 406us/step - loss: 0.1143
Epoch 272/1000
5/5 [==============================] - 0s 384us/step - loss: 0.1004
Epoch 273/1000
5/5 [==============================] - 0s 326us/step - loss: 0.1138
Epoch 274/1000
5/5 [==============================] - 0s 386us/step - loss: 0.1000
Epoch 275/1000
5/5 [==============================] - 0s 361us/step - loss: 0.1134
Epoch 276/1000
5/5 [==============================] - 0s 380us/step - loss: 0.0997
Epoch 277/1000
5/5 [==============================] - 0s 425us/step - loss: 0.1131
Epoch 278/1000
5/5 [==============================] - 0s 400us/step - loss: 0.0994
Epoch 279/1000
5/5 [==============================] - 0s 444us/step - loss: 0.1128
Epoch 280/1000
5/5 [==============================] - 0s 431us/step - loss: 0.0992
Epoch 281/1000
5/5 [==============================] - 0s 409us/step - loss: 0.1125
Epoch 282/1000
5/5 [==============================] - 0s 341us/step - loss: 0.0990
Epoc

Epoch 370/1000
5/5 [==============================] - 0s 386us/step - loss: 0.1004
Epoch 371/1000
5/5 [==============================] - 0s 361us/step - loss: 0.1152
Epoch 372/1000
5/5 [==============================] - 0s 411us/step - loss: 0.1004
Epoch 373/1000
5/5 [==============================] - 0s 366us/step - loss: 0.1152
Epoch 374/1000
5/5 [==============================] - 0s 415us/step - loss: 0.1003
Epoch 375/1000
5/5 [==============================] - 0s 351us/step - loss: 0.1151
Epoch 376/1000
5/5 [==============================] - 0s 380us/step - loss: 0.1002
Epoch 377/1000
5/5 [==============================] - 0s 370us/step - loss: 0.1150
Epoch 378/1000
5/5 [==============================] - 0s 405us/step - loss: 0.1001
Epoch 379/1000
5/5 [==============================] - 0s 381us/step - loss: 0.1149
Epoch 380/1000
5/5 [==============================] - 0s 392us/step - loss: 0.1000
Epoch 381/1000
5/5 [==============================] - 0s 426us/step - loss: 0.1148
Epoc

Epoch 469/1000
5/5 [==============================] - 0s 508us/step - loss: 0.0934
Epoch 470/1000
5/5 [==============================] - 0s 458us/step - loss: 0.0820
Epoch 471/1000
5/5 [==============================] - 0s 350us/step - loss: 0.0928
Epoch 472/1000
5/5 [==============================] - 0s 351us/step - loss: 0.0815
Epoch 473/1000
5/5 [==============================] - 0s 379us/step - loss: 0.0922
Epoch 474/1000
5/5 [==============================] - 0s 375us/step - loss: 0.0809
Epoch 475/1000
5/5 [==============================] - 0s 441us/step - loss: 0.0915
Epoch 476/1000
5/5 [==============================] - 0s 390us/step - loss: 0.0804
Epoch 477/1000
5/5 [==============================] - 0s 384us/step - loss: 0.0909
Epoch 478/1000
5/5 [==============================] - 0s 440us/step - loss: 0.0799
Epoch 479/1000
5/5 [==============================] - 0s 418us/step - loss: 0.0903
Epoch 480/1000
5/5 [==============================] - 0s 469us/step - loss: 0.0794
Epoc

Epoch 568/1000
5/5 [==============================] - 0s 427us/step - loss: 0.0597
Epoch 569/1000
5/5 [==============================] - 0s 361us/step - loss: 0.0664
Epoch 570/1000
5/5 [==============================] - 0s 501us/step - loss: 0.0593
Epoch 571/1000
5/5 [==============================] - 0s 371us/step - loss: 0.0659
Epoch 572/1000
5/5 [==============================] - 0s 398us/step - loss: 0.0590
Epoch 573/1000
5/5 [==============================] - 0s 381us/step - loss: 0.0655
Epoch 574/1000
5/5 [==============================] - 0s 456us/step - loss: 0.0586
Epoch 575/1000
5/5 [==============================] - 0s 473us/step - loss: 0.0651
Epoch 576/1000
5/5 [==============================] - 0s 385us/step - loss: 0.0583
Epoch 577/1000
5/5 [==============================] - 0s 392us/step - loss: 0.0647
Epoch 578/1000
5/5 [==============================] - 0s 486us/step - loss: 0.0579
Epoch 579/1000
5/5 [==============================] - 0s 393us/step - loss: 0.0643
Epoc

Epoch 667/1000
5/5 [==============================] - 0s 406us/step - loss: 0.0500
Epoch 668/1000
5/5 [==============================] - 0s 398us/step - loss: 0.0453
Epoch 669/1000
5/5 [==============================] - 0s 367us/step - loss: 0.0497
Epoch 670/1000
5/5 [==============================] - 0s 491us/step - loss: 0.0451
Epoch 671/1000
5/5 [==============================] - 0s 521us/step - loss: 0.0495
Epoch 672/1000
5/5 [==============================] - 0s 336us/step - loss: 0.0449
Epoch 673/1000
5/5 [==============================] - 0s 372us/step - loss: 0.0492
Epoch 674/1000
5/5 [==============================] - 0s 377us/step - loss: 0.0446
Epoch 675/1000
5/5 [==============================] - 0s 394us/step - loss: 0.0489
Epoch 676/1000
5/5 [==============================] - 0s 411us/step - loss: 0.0444
Epoch 677/1000
5/5 [==============================] - 0s 359us/step - loss: 0.0487
Epoch 678/1000
5/5 [==============================] - 0s 422us/step - loss: 0.0442
Epoc

Epoch 766/1000
5/5 [==============================] - 0s 388us/step - loss: 0.0349
Epoch 767/1000
5/5 [==============================] - 0s 386us/step - loss: 0.0378
Epoch 768/1000
5/5 [==============================] - 0s 470us/step - loss: 0.0347
Epoch 769/1000
5/5 [==============================] - 0s 586us/step - loss: 0.0376
Epoch 770/1000
5/5 [==============================] - 0s 442us/step - loss: 0.0345
Epoch 771/1000
5/5 [==============================] - 0s 369us/step - loss: 0.0374
Epoch 772/1000
5/5 [==============================] - 0s 419us/step - loss: 0.0343
Epoch 773/1000
5/5 [==============================] - 0s 389us/step - loss: 0.0372
Epoch 774/1000
5/5 [==============================] - 0s 371us/step - loss: 0.0341
Epoch 775/1000
5/5 [==============================] - 0s 365us/step - loss: 0.0370
Epoch 776/1000
5/5 [==============================] - 0s 365us/step - loss: 0.0339
Epoch 777/1000
5/5 [==============================] - 0s 394us/step - loss: 0.0367
Epoc

Epoch 865/1000
5/5 [==============================] - 0s 374us/step - loss: 0.0283
Epoch 866/1000
5/5 [==============================] - 0s 378us/step - loss: 0.0262
Epoch 867/1000
5/5 [==============================] - 0s 393us/step - loss: 0.0281
Epoch 868/1000
5/5 [==============================] - 0s 440us/step - loss: 0.0261
Epoch 869/1000
5/5 [==============================] - 0s 399us/step - loss: 0.0280
Epoch 870/1000
5/5 [==============================] - 0s 342us/step - loss: 0.0259
Epoch 871/1000
5/5 [==============================] - 0s 431us/step - loss: 0.0278
Epoch 872/1000
5/5 [==============================] - 0s 445us/step - loss: 0.0258
Epoch 873/1000
5/5 [==============================] - 0s 379us/step - loss: 0.0276
Epoch 874/1000
5/5 [==============================] - 0s 363us/step - loss: 0.0256
Epoch 875/1000
5/5 [==============================] - 0s 348us/step - loss: 0.0275
Epoch 876/1000
5/5 [==============================] - 0s 407us/step - loss: 0.0255
Epoc

Epoch 964/1000
5/5 [==============================] - 0s 417us/step - loss: 0.0190
Epoch 965/1000
5/5 [==============================] - 0s 398us/step - loss: 0.0201
Epoch 966/1000
5/5 [==============================] - 0s 406us/step - loss: 0.0189
Epoch 967/1000
5/5 [==============================] - 0s 384us/step - loss: 0.0193
Epoch 968/1000
5/5 [==============================] - 0s 371us/step - loss: 0.0181
Epoch 969/1000
5/5 [==============================] - 0s 405us/step - loss: 0.0185
Epoch 970/1000
5/5 [==============================] - 0s 383us/step - loss: 0.0180
Epoch 971/1000
5/5 [==============================] - 0s 361us/step - loss: 0.0191
Epoch 972/1000
5/5 [==============================] - 0s 371us/step - loss: 0.0179
Epoch 973/1000
5/5 [==============================] - 0s 348us/step - loss: 0.0190
Epoch 974/1000
5/5 [==============================] - 0s 407us/step - loss: 0.0178
Epoch 975/1000
5/5 [==============================] - 0s 336us/step - loss: 0.0182
Epoc

In [6]:
model.predict(np.array([[1,5]]))

array([[5.8748875]], dtype=float32)

In [7]:
model.predict(np.array([[2,5]]))

array([[6.851327]], dtype=float32)

In [8]:
model.predict(np.array([[1,2]]))

array([[2.9547572]], dtype=float32)

In [9]:
model.predict(np.array([[2,2]]))

array([[3.9311967]], dtype=float32)

In [10]:
model.predict(np.array([[100,-250]]))

array([[34.664253]], dtype=float32)