In [1]:
from keras.models import Sequential
from keras import optimizers
from keras.layers import Dense, Activation

import numpy as np

Using TensorFlow backend.


In [2]:
X = np.array([[0,3], [2,2], [1,5], [2,4], [-1,10], [100, 100]])

In [12]:
model=Sequential()
model.add(Dense(units=2, activation='relu'))
model.add(Dense(units=256, activation='relu'))
model.add(Dense(units=1))

#sgd = optimizers.SGD(lr=0.02, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer='sgd')


In [13]:
Y=np.array([3,4,6,6,9, 200])

In [14]:
model.fit(X, Y, epochs=1000)

Epoch 1/1000
6/6 [==============================] - 1s 84ms/step - loss: 6696.8008
Epoch 2/1000
6/6 [==============================] - 0s 282us/step - loss: 6618.1040
Epoch 3/1000
6/6 [==============================] - 0s 349us/step - loss: 6258.9487
Epoch 4/1000
6/6 [==============================] - 0s 366us/step - loss: 6158722560.0000
Epoch 5/1000
6/6 [==============================] - 0s 313us/step - loss: 38349376.0000
Epoch 6/1000
6/6 [==============================] - 0s 340us/step - loss: 417461.0000
Epoch 7/1000
6/6 [==============================] - 0s 299us/step - loss: 401137.5000
Epoch 8/1000
6/6 [==============================] - 0s 299us/step - loss: 385460.5000
Epoch 9/1000
6/6 [==============================] - 0s 287us/step - loss: 370404.2500
Epoch 10/1000
6/6 [==============================] - 0s 290us/step - loss: 355944.2188
Epoch 11/1000
6/6 [==============================] - 0s 332us/step - loss: 342056.7812
Epoch 12/1000
6/6 [==============================] - 

Epoch 96/1000
6/6 [==============================] - 0s 340us/step - loss: 16111.8643
Epoch 97/1000
6/6 [==============================] - 0s 310us/step - loss: 15681.8252
Epoch 98/1000
6/6 [==============================] - 0s 304us/step - loss: 15268.8174
Epoch 99/1000
6/6 [==============================] - 0s 278us/step - loss: 14872.1670
Epoch 100/1000
6/6 [==============================] - 0s 389us/step - loss: 14491.2188
Epoch 101/1000
6/6 [==============================] - 0s 311us/step - loss: 14125.3594
Epoch 102/1000
6/6 [==============================] - 0s 356us/step - loss: 13773.9873
Epoch 103/1000
6/6 [==============================] - 0s 337us/step - loss: 13436.5303
Epoch 104/1000
6/6 [==============================] - 0s 331us/step - loss: 13112.4365
Epoch 105/1000
6/6 [==============================] - 0s 285us/step - loss: 12801.1758
Epoch 106/1000
6/6 [==============================] - 0s 285us/step - loss: 12502.2422
Epoch 107/1000
6/6 [===========================

6/6 [==============================] - 0s 317us/step - loss: 5486.0903
Epoch 192/1000
6/6 [==============================] - 0s 390us/step - loss: 5476.8345
Epoch 193/1000
6/6 [==============================] - 0s 331us/step - loss: 5467.9438
Epoch 194/1000
6/6 [==============================] - 0s 291us/step - loss: 5459.4053
Epoch 195/1000
6/6 [==============================] - 0s 345us/step - loss: 5451.2056
Epoch 196/1000
6/6 [==============================] - 0s 312us/step - loss: 5443.3301
Epoch 197/1000
6/6 [==============================] - 0s 344us/step - loss: 5435.7671
Epoch 198/1000
6/6 [==============================] - 0s 336us/step - loss: 5428.5034
Epoch 199/1000
6/6 [==============================] - 0s 292us/step - loss: 5421.5269
Epoch 200/1000
6/6 [==============================] - 0s 364us/step - loss: 5414.8267
Epoch 201/1000
6/6 [==============================] - 0s 358us/step - loss: 5408.3916
Epoch 202/1000
6/6 [==============================] - 0s 312us/step -

Epoch 287/1000
6/6 [==============================] - 0s 321us/step - loss: 5257.1655
Epoch 288/1000
6/6 [==============================] - 0s 352us/step - loss: 5256.9741
Epoch 289/1000
6/6 [==============================] - 0s 332us/step - loss: 5256.7905
Epoch 290/1000
6/6 [==============================] - 0s 326us/step - loss: 5256.6143
Epoch 291/1000
6/6 [==============================] - 0s 333us/step - loss: 5256.4448
Epoch 292/1000
6/6 [==============================] - 0s 345us/step - loss: 5256.2817
Epoch 293/1000
6/6 [==============================] - 0s 377us/step - loss: 5256.1255
Epoch 294/1000
6/6 [==============================] - 0s 320us/step - loss: 5255.9751
Epoch 295/1000
6/6 [==============================] - 0s 364us/step - loss: 5255.8315
Epoch 296/1000
6/6 [==============================] - 0s 306us/step - loss: 5255.6929
Epoch 297/1000
6/6 [==============================] - 0s 303us/step - loss: 5255.5601
Epoch 298/1000
6/6 [==============================] - 

Epoch 383/1000
6/6 [==============================] - 0s 339us/step - loss: 5252.4331
Epoch 384/1000
6/6 [==============================] - 0s 338us/step - loss: 5252.4292
Epoch 385/1000
6/6 [==============================] - 0s 311us/step - loss: 5252.4253
Epoch 386/1000
6/6 [==============================] - 0s 307us/step - loss: 5252.4219
Epoch 387/1000
6/6 [==============================] - 0s 291us/step - loss: 5252.4185
Epoch 388/1000
6/6 [==============================] - 0s 308us/step - loss: 5252.4150
Epoch 389/1000
6/6 [==============================] - 0s 334us/step - loss: 5252.4126
Epoch 390/1000
6/6 [==============================] - 0s 366us/step - loss: 5252.4082
Epoch 391/1000
6/6 [==============================] - 0s 332us/step - loss: 5252.4058
Epoch 392/1000
6/6 [==============================] - 0s 321us/step - loss: 5252.4023
Epoch 393/1000
6/6 [==============================] - 0s 341us/step - loss: 5252.4009
Epoch 394/1000
6/6 [==============================] - 

Epoch 479/1000
6/6 [==============================] - 0s 301us/step - loss: 5252.3354
Epoch 480/1000
6/6 [==============================] - 0s 322us/step - loss: 5252.3350
Epoch 481/1000
6/6 [==============================] - 0s 362us/step - loss: 5252.3350
Epoch 482/1000
6/6 [==============================] - 0s 375us/step - loss: 5252.3350
Epoch 483/1000
6/6 [==============================] - 0s 468us/step - loss: 5252.3350
Epoch 484/1000
6/6 [==============================] - 0s 272us/step - loss: 5252.3354
Epoch 485/1000
6/6 [==============================] - 0s 284us/step - loss: 5252.3345
Epoch 486/1000
6/6 [==============================] - 0s 325us/step - loss: 5252.3354
Epoch 487/1000
6/6 [==============================] - 0s 354us/step - loss: 5252.3354
Epoch 488/1000
6/6 [==============================] - 0s 404us/step - loss: 5252.3350
Epoch 489/1000
6/6 [==============================] - 0s 309us/step - loss: 5252.3345
Epoch 490/1000
6/6 [==============================] - 

Epoch 575/1000
6/6 [==============================] - 0s 324us/step - loss: 5252.3325
Epoch 576/1000
6/6 [==============================] - 0s 295us/step - loss: 5252.3335
Epoch 577/1000
6/6 [==============================] - 0s 368us/step - loss: 5252.3335
Epoch 578/1000
6/6 [==============================] - 0s 325us/step - loss: 5252.3330
Epoch 579/1000
6/6 [==============================] - 0s 334us/step - loss: 5252.3330
Epoch 580/1000
6/6 [==============================] - 0s 329us/step - loss: 5252.3335
Epoch 581/1000
6/6 [==============================] - 0s 310us/step - loss: 5252.3335
Epoch 582/1000
6/6 [==============================] - 0s 290us/step - loss: 5252.3335
Epoch 583/1000
6/6 [==============================] - 0s 347us/step - loss: 5252.3330
Epoch 584/1000
6/6 [==============================] - 0s 405us/step - loss: 5252.3335
Epoch 585/1000
6/6 [==============================] - 0s 366us/step - loss: 5252.3335
Epoch 586/1000
6/6 [==============================] - 

Epoch 671/1000
6/6 [==============================] - 0s 362us/step - loss: 5252.3335
Epoch 672/1000
6/6 [==============================] - 0s 312us/step - loss: 5252.3335
Epoch 673/1000
6/6 [==============================] - 0s 309us/step - loss: 5252.3335
Epoch 674/1000
6/6 [==============================] - 0s 329us/step - loss: 5252.3335
Epoch 675/1000
6/6 [==============================] - 0s 376us/step - loss: 5252.3330
Epoch 676/1000
6/6 [==============================] - 0s 318us/step - loss: 5252.3330
Epoch 677/1000
6/6 [==============================] - 0s 344us/step - loss: 5252.3335
Epoch 678/1000
6/6 [==============================] - 0s 352us/step - loss: 5252.3330
Epoch 679/1000
6/6 [==============================] - 0s 354us/step - loss: 5252.3330
Epoch 680/1000
6/6 [==============================] - 0s 331us/step - loss: 5252.3330
Epoch 681/1000
6/6 [==============================] - 0s 314us/step - loss: 5252.3335
Epoch 682/1000
6/6 [==============================] - 

Epoch 767/1000
6/6 [==============================] - 0s 310us/step - loss: 5252.3335
Epoch 768/1000
6/6 [==============================] - 0s 295us/step - loss: 5252.3340
Epoch 769/1000
6/6 [==============================] - 0s 364us/step - loss: 5252.3325
Epoch 770/1000
6/6 [==============================] - 0s 332us/step - loss: 5252.3335
Epoch 771/1000
6/6 [==============================] - 0s 344us/step - loss: 5252.3335
Epoch 772/1000
6/6 [==============================] - 0s 343us/step - loss: 5252.3335
Epoch 773/1000
6/6 [==============================] - 0s 321us/step - loss: 5252.3340
Epoch 774/1000
6/6 [==============================] - 0s 305us/step - loss: 5252.3335
Epoch 775/1000
6/6 [==============================] - 0s 339us/step - loss: 5252.3330
Epoch 776/1000
6/6 [==============================] - 0s 337us/step - loss: 5252.3335
Epoch 777/1000
6/6 [==============================] - 0s 307us/step - loss: 5252.3325
Epoch 778/1000
6/6 [==============================] - 

Epoch 863/1000
6/6 [==============================] - 0s 349us/step - loss: 5252.3335
Epoch 864/1000
6/6 [==============================] - 0s 385us/step - loss: 5252.3335
Epoch 865/1000
6/6 [==============================] - 0s 337us/step - loss: 5252.3335
Epoch 866/1000
6/6 [==============================] - 0s 325us/step - loss: 5252.3335
Epoch 867/1000
6/6 [==============================] - 0s 305us/step - loss: 5252.3335
Epoch 868/1000
6/6 [==============================] - 0s 311us/step - loss: 5252.3335
Epoch 869/1000
6/6 [==============================] - 0s 311us/step - loss: 5252.3335
Epoch 870/1000
6/6 [==============================] - 0s 320us/step - loss: 5252.3335
Epoch 871/1000
6/6 [==============================] - 0s 317us/step - loss: 5252.3335
Epoch 872/1000
6/6 [==============================] - 0s 320us/step - loss: 5252.3335
Epoch 873/1000
6/6 [==============================] - 0s 314us/step - loss: 5252.3335
Epoch 874/1000
6/6 [==============================] - 

Epoch 959/1000
6/6 [==============================] - 0s 311us/step - loss: 5252.3335
Epoch 960/1000
6/6 [==============================] - 0s 344us/step - loss: 5252.3335
Epoch 961/1000
6/6 [==============================] - 0s 349us/step - loss: 5252.3335
Epoch 962/1000
6/6 [==============================] - 0s 322us/step - loss: 5252.3335
Epoch 963/1000
6/6 [==============================] - 0s 318us/step - loss: 5252.3335
Epoch 964/1000
6/6 [==============================] - 0s 351us/step - loss: 5252.3335
Epoch 965/1000
6/6 [==============================] - 0s 292us/step - loss: 5252.3335
Epoch 966/1000
6/6 [==============================] - 0s 380us/step - loss: 5252.3335
Epoch 967/1000
6/6 [==============================] - 0s 349us/step - loss: 5252.3335
Epoch 968/1000
6/6 [==============================] - 0s 314us/step - loss: 5252.3335
Epoch 969/1000
6/6 [==============================] - 0s 338us/step - loss: 5252.3335
Epoch 970/1000
6/6 [==============================] - 

In [6]:
model.predict(np.array([[1,5]]))

array([[37.99991]], dtype=float32)

In [7]:
model.predict(np.array([[2,5]]))

array([[37.99991]], dtype=float32)

In [8]:
model.predict(np.array([[1,2]]))

array([[37.99991]], dtype=float32)

In [9]:
model.predict(np.array([[2,2]]))

array([[37.99991]], dtype=float32)

In [10]:
model.predict(np.array([[100,-250]]))

array([[37.99991]], dtype=float32)